package com.yingshi.server.common.exception;

public enum ErrorCode {
    ALBUM_ASSIGNMENT_INVALID,
    ALBUM_NOT_FOUND,
    AUTH_INVALID_CREDENTIALS,
    AUTH_SESSION_INVALID,
    AUTH_TOKEN_EXPIRED,
    AUTH_UNAUTHORIZED,
    COMMENT_NOT_FOUND,
    COMMENT_SCOPE_MISMATCH,
    COMMENT_TARGET_NOT_FOUND,
    FORBIDDEN,
    MEDIA_NOT_FOUND,
    NOT_FOUND,
    POST_COVER_INVALID,
    POST_MEDIA_ORDER_INVALID,
    POST_NOT_FOUND,
    VALIDATION_ERROR,
    METHOD_NOT_ALLOWED,
    SERVER_ERROR
}
